spring:
  application:
    name: inventory-service          # Service identity — Config Server uses this to serve inventory-service.yml

  config:
    import: "optional:configserver:http://localhost:8888"   # Fetch remote config on startup

  cloud:
    config:
      username: config-admin         # Config Server basic auth
      password: config-secret-2024

  datasource:
    url: jdbc:postgresql://localhost:5433/inventory_db
    username: oms_user
    password: oms_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop          # Auto creates tables on start, drops on stop
    show-sql: true                   # Prints SQL queries to console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: Inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.oms.inventory_service.kafka.dto.OrderCreatedEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always