spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: config-admin
      password: config-secret-2024

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
